---
- name: Obtener token
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Solicitar token
      uri:
        url: "http://10.100.32.114:9090/token"
        method: POST
        body_format: form-urlencoded
        body:
          username: "admin"
          password: "admin$2025"
        return_content: true
        status_code: 200
      register: resultado

    - name: Mostrar token
      debug:
        var: resultado.json
